[package]
name    = "dw1000"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]
edition = "2018"

description   = "Driver for the Decawave DW1000 UWB wireless transceiver chip, providing radio communication based on IEEE 802.15.4 and distance measurement"
documentation = "https://docs.rs/dw1000"
repository    = "https://github.com/braun-robotics/rust-dw1000"
license       = "0BSD"
readme        = "README.md"
categories    = ["embedded", "hardware-support", "no-std"]
keywords      = ["decawave", "dw1000", "radio", "embedded-hal", "embedded-hal-driver"]


[badges]
travis-ci = { repository = "braun-robotics/rust-dw1000" }


[dependencies]
embedded-hal = "0.2.2"
ieee802154   = "0.1.0"
nb           = "0.1.1"
serde        = { version = "1.0.79", default-features = false }
serde_derive = "1.0.79"
ssmarshal    = { version = "1.0", default-features = false }

[dev-dependencies]
cortex-m-rt       = "0.6.7"
dwm1001           = { version = "0.1.1", features = ["dev"] }
heapless          = "0.4.2"
panic-semihosting = "0.5.1"
void              = { version = "1.0.2", default-features = false }

[features]
semihosting = ["dwm1001/semihosting"]
